"""Add motivational_quote to User

Revision ID: 1da02defbbd8
Revises: 3f02a68aca8a
Create Date: 2025-06-05 10:42:50.816253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da02defbbd8'
down_revision = '3f02a68aca8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivational_quote', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('motivational_quote')

    # ### end Alembic commands ###
