"""Make normalized_name unique and not null

Revision ID: 31ce5371a50e
Revises: 91376e40ecb7
Create Date: 2025-06-14 09:47:20.434237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ce5371a50e'
down_revision = '91376e40ecb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.alter_column('normalized_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint('uq_forums_normalized_name', ['normalized_name'])
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.drop_constraint('uq_forums_normalized_name', type_='unique')
        batch_op.alter_column('normalized_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('_alembic_tmp_forums',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('university_domain', sa.VARCHAR(length=120), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('normalized_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_forums_normalized_name')),
    sa.UniqueConstraint('university_domain')
    )
    # ### end Alembic commands ###
