"""Add university and faculty to User

Revision ID: 378405336853
Revises: d86eb3845e0e
Create Date: 2025-06-05 10:01:27.686227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378405336853'
down_revision = 'd86eb3845e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('faculty', sa.String(length=100), nullable=True))
        batch_op.drop_column('hobbies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hobbies', sa.TEXT(), nullable=True))
        batch_op.drop_column('faculty')
        batch_op.drop_column('university')

    # ### end Alembic commands ###
