"""Add icon and image_url to Committee

Revision ID: 3950fad31ac6
Revises: 68ed6bdb9bd7
Create Date: 2025-07-01 09:50:48.745276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3950fad31ac6'
down_revision = '68ed6bdb9bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
