"""Add logo_url to Forum

Revision ID: 3b332dfcc46d
Revises: 3950fad31ac6
Create Date: 2025-07-01 09:57:16.279076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b332dfcc46d'
down_revision = '3950fad31ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
