"""Add parent_id for threaded replies

Revision ID: 4d091baa6b71
Revises: b616c1355432
Create Date: 2025-06-05 11:56:34.929533
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4d091baa6b71'
down_revision = 'b616c1355432'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_comments_parent_id_comments',  # Explicitly named constraint!
            'comments',  # Referenced table
            ['parent_id'],  # Local column
            ['id']  # Remote column
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_parent_id_comments', type_='foreignkey')
        batch_op.drop_column('parent_id')
    # ### end Alembic commands ###

