"""Add slug to Committee

Revision ID: 68ed6bdb9bd7
Revises: a250d71c4aca
Create Date: 2025-06-30 09:59:47.277546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ed6bdb9bd7'
down_revision = 'a250d71c4aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint('uq_committees_slug', ['slug'])  # ✅ Named constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
