"""Add meetup_rsvps association table

Revision ID: 6f5a9522a146
Revises: c3072f5f1c7e
Create Date: 2025-06-21 10:25:48.055955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5a9522a146'
down_revision = 'c3072f5f1c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetup_rsvps',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meetup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('user_id', 'meetup_id', name='unique_user_meetup_rsvp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetup_rsvps')
    # ### end Alembic commands ###
