"""Add Forum model and forum_id to Post

Revision ID: 727edd83f86a
Revises: 852800b590d9
Create Date: 2025-06-12 11:17:07.838402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727edd83f86a'
down_revision = '852800b590d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('university_domain', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('university_domain')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forum_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_posts_forum_id', 'forums', ['forum_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_forum_id', type_='foreignkey')
        batch_op.drop_column('forum_id')

    op.drop_table('forums')
    # ### end Alembic commands ###
