"""Add unit_code column to Meetup

Revision ID: 865e1a34ecc9
Revises: 6f5a9522a146
Create Date: 2025-06-21 15:31:13.985649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865e1a34ecc9'
down_revision = '6f5a9522a146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.drop_column('unit_code')

    # ### end Alembic commands ###
