"""Add unique constraint to student_number

Revision ID: 90bd542ae76a
Revises: 31e89e66de5d
Create Date: 2025-06-06 20:39:12.767867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bd542ae76a'
down_revision = '31e89e66de5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('student_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        # 🔧 Add explicit name to the unique constraint!
        batch_op.create_unique_constraint('uq_users_student_number', ['student_number'])
        batch_op.drop_column('full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), nullable=False))
        # 🔧 Drop the constraint by name
        batch_op.drop_constraint('uq_users_student_number', type_='unique')
        batch_op.alter_column('student_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('display_name')
    # ### end Alembic commands ###
