"""Add email and phone to TutorAd

Revision ID: a250d71c4aca
Revises: 2aecdf4e983e
Create Date: 2025-06-27 20:56:26.492834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a250d71c4aca'
down_revision = '2aecdf4e983e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('tutor_ad', schema=None) as batch_op:
        # Add 'email' column with a temporary default to satisfy SQLite constraint
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False, server_default='example@example.com'))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_ad', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
