"""Add type field to Meetup

Revision ID: c3072f5f1c7e
Revises: a42e080673bc
Create Date: 2025-06-21 10:20:00.265034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3072f5f1c7e'
down_revision = 'a42e080673bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
