"""Add profile fields to User model

Revision ID: d86eb3845e0e
Revises: 21e2006d7f53
Create Date: 2025-06-05 09:32:54.438057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86eb3845e0e'
down_revision = '21e2006d7f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hobbies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cover_picture')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('phone')
        batch_op.drop_column('job_title')
        batch_op.drop_column('hobbies')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
