"""Add quote column to User

Revision ID: f81267b9b290
Revises: afba31f30f37
Create Date: 2025-06-06 16:21:08.780383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81267b9b290'
down_revision = 'afba31f30f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote', sa.Text(), nullable=True))
        batch_op.drop_column('motivational_quote')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivational_quote', sa.TEXT(), nullable=True))
        batch_op.drop_column('quote')

    # ### end Alembic commands ###
